import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserProvider from "@/providers/UserProvider";
import { Toaster } from "react-hot-toast";
import {Inter} from "next/font/google";
import MiniSidebar from "./Components/MiniSidebar/MiniSidebar";
import Header from "./Components/Header/Header";
import SidebarProvider from "@/providers/SidebarProvider";
import MainContentLayout from "@/providers/MainContentLayout";
import MainLayout from "@/providers/MainLayout";

const inter = Inter({
  subsets:["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserProvider>
        <Toaster position="top-center"/>
        <div className="h-full flex overflow-hidden">
          <MiniSidebar/>
          <div className="flex-1 flex flex-col"></div>
            <Header />
            <MainContentLayout>
              <MainLayout>{children}</MainLayout>
              <SidebarProvider/>
            </MainContentLayout>
        </div>
        {children}
      </UserProvider>
      </body>
    </html>
  );
}
